version: 2.1

orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@2.0.2

jobs:
  unit_test:
    docker:
      - image: cirrusci/flutter:stable
    environment:
      - FLUTTER_CHANNEL: stable
      - FLUTTER_VERSION: latest
    steps:
      - checkout
      - flutter/install_sdk
      - run:
          name: Install Flutter dependencies
          command: |
            cd ~/project/calculadora
            flutter pub get
      - run:
          name: Run tests
          command: |
            cd ~/project/calculadora
            flutter test
workflows:
  test:
    jobs:
      - unit_test
