version: 2.1

orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@2.0.2

jobs:
  unit_test:
    docker:
      - image: cirrusci/flutter:stable
    working_directory: ~/project/calculadora
    environment:
      - FLUTTER_CHANNEL: stable
      - FLUTTER_VERSION: latest
    steps:
      - checkout
      - flutter/install_sdk: 
          version: 3.7.9
      - flutter/install_pub:
          cache-version: v1
      - run:
          name: Change ownership of Flutter SDK
          command: sudo chown -R circleci:circleci /root/usr/development/flutter        
      - run:
          name: Install Flutter dependencies
          command: | 
            cd ./calculadora
            flutter pub get
      - run:
          name: Run tests
          command: | 
            cd ./calculadora
            flutter test
workflows:
  test:
    jobs:
      - unit_test
