version: 2.1

jobs:
  unit_test:
    docker:
      - image: cirrusci/flutter:stable
    environment:
      - FLUTTER_CHANNEL: stable
      - FLUTTER_VERSION: latest
    steps:
      - checkout
      - run:
          name: Install Flutter dependencies
          run: flutter upgrade
          command: |
            cd ~/project/calculadora
            flutter pub get
      - run:
          name: Run tests
          command: |
            cd ~/project/calculadora
            flutter test
workflows:
  test:
    jobs:
      - unit_test
