version: 2.1

jobs:
  unit_test:
    docker:
      - image: mobiledevops/flutter-sdk-image:3.16.4
    environment:
      - FLUTTER_CHANNEL: stable
      - FLUTTER_VERSION: latest
    steps:
      - checkout
      - run: ls -a
      - run:
          name: Install Flutter dependencies
          command: |
            cd ~/project/calculadora
            flutter pub get
      - run:
          name: Run tests
          command: |
            cd ~/project/calculadora
            flutter test
workflows:
  test:
    jobs:
      - unit_test
